### ISSUE TITLE
Duplicate identifier 'Action'

### ISSUE THREAD

**Issue by lewispeel** [aikoven/redux-typescript-actions#4]
Hi,

I just copy and pasted your example but can't seem to get around the duplicate identifier I'm seeing;

```
// reducer.ts
import {Action} from 'redux';
import {isType, Action} from 'redux-typescript-actions';
```

Am I doing something wrong?

**Comment by lewispeel** [comment]
I removed the Action import from 'redux-typescript-actions' and it worked - although I had to turn 'strictNullChecks' off in my tsconfig but I'm sure I can change the example.

**Comment by aikoven** [comment]
I am so sorry, I've missed your issue!

You don't have to turn off `strictNullChecks`. If you want to use both `Action` types in a single module, you can go with:
```ts
import {Action as ReduxAction} from 'redux';
import {isType, Action} from 'redux-typescript-actions';
```
